apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client-app
spec:
  selector:
    matchLabels:
      app: yolo-client-app
  template:
    metadata:
      labels:
        app: yolo-client-app
    spec:
      containers:
      - name: client-container
        image: tashaops/docker-client:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-client-app
spec:
  selector:
    app: yolo-client-app
  ports:
  - port: 3000
    targetPort: 3000
        
