apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend-app
spec:
  selector:
    matchLabels:
      app: yolo-backend-app
  template:
    metadata:
      labels:
        app: yolo-backend-app
    spec:
      containers:
      - name: yolo-backend-app
        image: tashaops/docker-backend:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend-app
spec:
  selector:
    app: yolo-backend-app
  ports:
  - port: 5000
    targetPort: 5000

